### ISSUE TITLE
Compatibility with Laravel 5.5

### ISSUE THREAD

**Issue by filisko** [chelout/laravel-relationship-events#1]
Hi @chelout,
Is this compatible with Laravel 5.5 ? or it only works with Laravel 5.6 ?

It looks very nice.

**Comment by chelout** [comment]
Hi, actually it should be, but haven't tested. That's why there are constraints in composer.json
Are you running 5.5? Not updating because LTS?

**Comment by filisko** [comment]
I didn't update yet because I have dependencies that only work with 5.5 :(

**Comment by chelout** [comment]
I see...
Ok, i'll try to revert constraints for 5.5 tomorrow.

**Comment by chelout** [comment]
@filisko what's your php version?

**Comment by filisko** [comment]
I'm running 7.2.3

**Comment by chelout** [comment]
You can try latest [release](https://github.com/chelout/laravel-relationship-events/releases/tag/v0.3) with Laravel 5.5 support

**Comment by filisko** [comment]
Thank you @chelout. That's great.

**Comment by chelout** [comment]
You are welcome, let me know if something goes wrong with the package.
