### ISSUE TITLE
Attached event's $parent (model) is doesn't include attachments.

### ISSUE THREAD

**Issue by NizarBlond** [chelout/laravel-relationship-events#12]
Hi,

I have a User and Permission classes. 

User has the Trait: HasMorphToManyEvents.

I added the attached event under boot:

```
static::morphToManyAttached(function ($relation, $model, $ids, $attributes = []) {
    print_r($ids); // includes the added permission
    print_r($model->permissions->pluck('id')->toArray()); / doesn't include the permission
});
```

I think the updated model should be sent to the Event (e.g. static::find($model->id)) instead of passing $model.

Or did I miss anything?

**Comment by chelout** [comment]
Could you show me both classes?

**Comment by chelout** [comment]
Closed due inactivity

**Comment by chelout** [comment]
Closed due inactivity

**Comment by matthewmnewman** [comment]
I believe what he means is that the $ids passed through contain the new permissions as intended but the $model does not contain the updated $ids within the parent model instance.

I was using this method to create a Model observer to save any activity on the BelongsToManySynced event. Ideally, it would be helpful to retrieve the updated $ids through the $parent model as that would mean I could dynamically get the relations and save them to my activity table.
