### ISSUE TITLE
distinguishing multiple relationships in same model

### ISSUE THREAD

**Issue by textoo** [chelout/laravel-relationship-events#17]
Hello,

i have a model with 2 belongsToMany relationships, so this code : 

`static::belongsToManyDetached(function($relation,$parent,$ids){
});`

catch the 2 relationships when detached and i can't figure how to distinguish which one fired the event.

EDIT:

i was expecting $relation to return the class name of the target model, but in my case i get "insertUpdateData" . 
Now i think this is the name of a function from a CMS i use that update relationship data directly so the event is not aware of the target model.
So this can be an issue of the CMS.

**Comment by chelout** [comment]
Actually, $relation will have relation name, not a class name. I guess "insertUpdateData" is a relation name from this CMS. Ping me if we should dig a little more in it.

**Comment by textoo** [comment]
@chelout thank you for your answer, 'insertUpdateData ' is effectively a name function from the CMS i use, so i have finally achieved my needs with a different approach: using a belongsToManySynced , i still don't get the relation name but i can act accordingly to my DB state, and that's fine for my purpose.

**Comment by chelout** [comment]
@textoo 👍🏻
