### ISSUE TITLE
Docs methods parameters are wrong

### ISSUE THREAD

**Issue by arall** [chelout/laravel-relationship-events#18]
For example: https://github.com/chelout/laravel-relationship-events/blob/master/doc/7-many-to-many-polymorphic.md

Markdown code:
```
static::morphedByManyAttached(function ($parent, $ids, $attributes) {
    Log::info("Post has been attached to tag {$parent->name}.");
});
```
Markdown text:

**MorphedByMany::attach**
* fires morphedByManyAttaching, morphedByManyAttached
* events have $relation name, $parent model, $attributes attaching model ids

**Comment by chelout** [comment]
Thanks! Could you make a PR?
