### ISSUE TITLE
Multi tenant support

### ISSUE THREAD

**Issue by fernandocoronatomf** [chelout/laravel-relationship-events#2]
Hi,

Thank you for the package... I tried to use it with a multi tenant package and as soon as I do

`  static::hasManySaved(function ($parent, $related) {
            dd('hello');
        });`

I can't even run migrations anymore, it says my database is not configured.

Any idea that can help me to figure out the problem?

**Comment by chelout** [comment]
Can you show me your model code?

**Comment by chelout** [comment]
And what package/version do you use as multi tenant?

**Comment by fernandocoronatomf** [comment]
The package I am using is

https://github.com/hyn/multi-tenant
