### ISSUE TITLE
HasMorphToManyEvents and HasMorphedByManyEvents in the same model

### ISSUE THREAD

**Issue by tobyjoiner** [chelout/laravel-relationship-events#38]
When trying to use:

```
use Chelout\RelationshipEvents\Concerns\HasMorphedByManyEvents;
use Chelout\RelationshipEvents\Concerns\HasMorphToManyEvents;

class Demo extends Model
{
  use HasMorphToManyEvents;
  use HasMorphedByManyEvents;
}
```
tells me Trait method 'newMorphToMany' will not be applied because it collides with 'HasMorphToManyEvents'.  

Is there an easy work around for this?

**Comment by v-bubar** [comment]
@chelout It doesn't work that way. Using `instead` and `as` as described in the documentation resolves the conflict formally, i.e. no error is raised, but in the end, only one of the traits is working. For example is this case `morphToMany...` events won't work.
```
use HasMorphedByManyEvents, HasMorphToManyEvents {
        HasMorphedByManyEvents::newMorphToMany insteadof HasMorphToManyEvents;
        HasMorphToManyEvents::newMorphToMany as newMorphToMany2;
    }
```
