### ISSUE TITLE
Using Observer needs to define extra events observables 

### ISSUE THREAD

**Issue by reefki** [chelout/laravel-relationship-events#9]
I spent an hour to find out that when using `Observer` you need to define extra observable events to the model so that the observer class can listen to those custom events like so:

```
/**
 * These are extra user-defined events observers may subscribe to.
 *
 * @var array
 */
protected $observables = [
    'belongsToManyAttaching',
    'belongsToManyAttached',
    'belongsToManyDetaching',
    'belongsToManyDetached',
];
```

Please update the docs.

**Comment by chelout** [comment]
Hi @reefki, thanks for your interest in this package. Actually you don't have to define extra events, just use HasRelationshipObservables trait for that.
I'll fix the docs a little bit later.

**Comment by reefki** [comment]
@chelout That's awesome! Thank you

**Comment by maslauskas** [comment]
I ran into this issue today and couldn't figure out why it's not working. Please add it to docs :)

**Comment by chelout** [comment]
@maslauskas added note about `HasRelationshipObservables` trait into the docs, thanks.

**Comment by ShaoZeMing** [comment]
ty
